version: '3.8'
services:
  app:
    image: vinayko/fastapi-template:latest  # Use the pushed Docker Hub image
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  # Wait for DB to be ready
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/urls  # Set DB connection URL
    networks:
      - app_network

  db:
    image: postgres:latest
    restart: always  # Ensure it restarts if it crashes
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: urls
    ports:
      - "5432:5432"
    healthcheck:  # Wait for DB to be ready before starting the app
      test: ["CMD-SHELL", "pg_isready -U user -d urls"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
