name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Debug Python Path and Installed Packages
        run: |
          which python3
          python3 --version
          pip list
      
      - name: Install Dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install --no-cache-dir --force-reinstall -r requirements.txt
      - name: Start PostgreSQL for Tests
        run: |
          docker run -d --name test-db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=urls -p 5432:5432 postgres:latest
          sleep 20
      - name: Run Tests
        run:  PYTHONPATH=$PWD python -m pytest --disable-warnings --rootdir=app app/tests --verbose
        
      - name: Build Docker Image
        run: docker build -t vinayko/fastapi-template:latest .
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
      - name: Push Docker Image
        run: docker push vinayko/fastapi-template:latest
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose version
      
      
      - name: Deploy with Docker Compose
        run: |
            docker compose -f docker-compose.yml down || true  # Stop existing containers if running
            docker compose -f docker-compose.yml pull          # Ensure images are up-to-date
            docker compose -f docker-compose.yml up -d        # Start the FastAPI + DB stack
        
      